spring.application.name=spring-authorization-server
server.port=9000
spring.security.oauth2.authorizationserver.issuer-uri=http://localhost:9000
spring.security.oauth2.authorizationserver.jwk.key-size=2048
spring.security.oauth2.authorizationserver.jwk.key-algorithm=RS256
spring.security.oauth2.authorizationserver.jwk.use=SIGNATURE
spring.security.oauth2.authorizationserver.jwk.generate-on-startup=true
spring.security.oauth2.authorizationserver.oidc.enabled=true
spring.security.oauth2.authorizationserver.oidc.user-info-always-included-in-id-token=true
spring.security.oauth2.authorizationserver.oidc.client-registration.enabled=true
logging.level.org.springframework.security=debug